export const strings = {
    welcomeMessage: 'Bem-vindo ao Banco Economia',
    myAccount: 'Minha Conta',
    pixKeys: 'Acessar área PIX',
    balanceLabel: 'Saldo:',
    balanceAmount: 'R$ 10.000,00',
    checkBalanceButton: 'Ver Saldo',
    transferButton: 'Transferências',
    extratoButton: 'Extrato',
    paymentsButton: 'Pagamentos',
    investmentsButton: 'Investimentos',
    signUpTitle: 'Registre-se',
    pixAreaTitle: 'Sua Area PIX',
    pixAreaCreate: 'Cadastrar chave PIX',
    pixAreaListPixKeys: 'Atualizar suas chaves PIX',
    pixArea: 'Enviar PIX',
    accountScreenTitle: 'Detalhes da conta',
    pixAreaSendPix: 'Enviar Pix',
  };
  