export const strings = {
    welcomeMessage: 'Bem-vindo ao Banco Economia',
    myAccount: 'Minha Conta',
    pixKeys: 'Acessar área PIX',
    balanceLabel: 'Saldo:',
    balanceAmount: 'R$ 10.000,00',
    checkBalanceButton: 'Ver Saldo',
    transferButton: 'Transferências',
    extratoButton: 'Extrato',
    paymentsButton: 'Pagamentos',
    investmentsButton: 'Investimentos',
    signUpTitle: 'Registre-se',
    pixAreaTitle: 'Sua Area PIX',
    pixAreaCreate: 'Cadastrar chave PIX',
    pixAreaListPixKeys: 'Atualizar suas chaves PIX',
    pixArea: 'Enviar PIX',
    accountScreenTitle: 'Detalhes da conta',
    pixAreaSendPix: 'Enviar Pix',
    loginTitle: 'Login',
    accountDetails: 'Detalhes da conta',
    accountDetailsEmail: 'Email:',
    accountDetailsTelefone: 'Telefone:',
    accountDetailsNome: 'Nome:',
    accountDetailsOcupacao: 'Ocupação:',
    accountDetailsEndereco: 'Endereço:',
    accountDetailsTipo: 'Tipo:',
    accountDetailsSaldo: 'Saldo:',
    accountDetailsR$: 'R$',
    accountDetailsReload: 'Atualizar Detalhes',
    accountDetailsError: 'Erro ao atualizar conta',
    accountUpdateFailed: 'Atualização falhou',
    accountDetailsUrlFoto: 'URL da foto',
    accountDetailsDelete: 'Deletar conta',
    pixAreaType: 'Tipo:',
    pixAreaKey: 'Chave:',
    pixAreaSendPixTitle: 'Enviar pix',
    reload: 'Recarregar',
    error: 'Erro',
  };
  